### ISSUE TITLE
selecting renegade exe hangs application

### ISSUE THREAD

**Issue by walksanatora** [cyberarm/w3d_hub_linux_launcher#8]
hello there. I found your project and find it interesting.
I tried to use it but when I select my `Renegade.exe` the entire application freezes until I manually kill it making me unable to select it.
I have already manually applied latest Tiberian Technologies though so if that is the issue let me know

**Comment by walksanatora** [comment]
okay so no it appears that I just have to move the file dialog out of the way and then I can manually press save after that to confirm

**Comment by walksanatora** [comment]
other issue I found. mod browser does not work... (it is just `HD Terminal Purchase Icons` repeated over and over again)

**Comment by cyberarm** [comment]
Hello there!
What operating system are you using?
I made some changes to how the `ask_file` is handled yesterday and haven't had time to check on Linux yet 😀

The mod manager hasn't gotten post the mockup stage, I should probably disable access to it in the meantime.

**Comment by walksanatora** [comment]
running resulted in
```
/home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/api/applications.rb:36:in `initialize': undefined method `sub' for 4289740581:Integer (NoMethodError)
Did you mean?  succ
        from /home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/api/applications.rb:11:in `new'
        from /home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/api/applications.rb:11:in `block in initialize'
        from /home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/api/applications.rb:11:in `each'
        from /home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/api/applications.rb:11:in `initialize'
        from /home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/states/boot.rb:265:in `new'
        from /home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/states/boot.rb:265:in `load_offline_applications_list'
        from /home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/states/boot.rb:55:in `update'
        from /home/walksanator/git/ruby/cyberarm_engine/lib/cyberarm_engine/window.rb:81:in `update'
        from /home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/window.rb:27:in `update'
        from /home/walksanator/.local/share/gem/ruby/3.0.0/gems/gosu-1.4.6/lib/gosu/patches.rb:64:in `tick'
        from w3d_hub_linux_launcher.rb:177:in `<main>
        ```

**Comment by cyberarm** [comment]
Should be fixed now.
It will require being connected to the internet at least once so that the application data can get re-saved correctly.

**Comment by walksanatora** [comment]
new issue (I even re-cloned)
```
/home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/pages/games.rb:10:in `setup': undefined method `channels' for nil:NilClass (NoMethodError)
        from /home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/states/interface.rb:194:in `page'
        from /home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/states/interface.rb:119:in `setup'
        from /home/walksanator/git/ruby/cyberarm_engine/lib/cyberarm_engine/window.rb:155:in `push_state'
        from /home/walksanator/git/ruby/cyberarm_engine/lib/cyberarm_engine/common.rb:4:in `push_state'
        from /home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/states/boot.rb:75:in `update'
        from /home/walksanator/git/ruby/cyberarm_engine/lib/cyberarm_engine/window.rb:81:in `update'
        from /home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/window.rb:27:in `update'
        from /home/walksanator/.local/share/gem/ruby/3.0.0/gems/gosu-1.4.6/lib/gosu/patches.rb:64:in `tick'
        from w3d_hub_linux_launcher.rb:177:in `<main>'
```

**Comment by cyberarm** [comment]
Should be fixed now 🙂

**Comment by walksanatora** [comment]
```
/home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/pages/games.rb:10:in `setup': undefined method `channels' for nil:NilClass (NoMethodError)
        from /home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/states/interface.rb:194:in `page'
        from /home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/states/interface.rb:119:in `setup'
        from /home/walksanator/git/ruby/cyberarm_engine/lib/cyberarm_engine/window.rb:155:in `push_state'
        from /home/walksanator/git/ruby/cyberarm_engine/lib/cyberarm_engine/common.rb:4:in `push_state'
        from /home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/states/boot.rb:84:in `update'
        from /home/walksanator/git/ruby/cyberarm_engine/lib/cyberarm_engine/window.rb:81:in `update'
        from /home/walksanator/git/ruby/w3d_hub_linux_launcher/lib/window.rb:27:in `update'
        from /home/walksanator/.local/share/gem/ruby/3.0.0/gems/gosu-1.4.6/lib/gosu/patches.rb:64:in `tick'
        from w3d_hub_linux_launcher.rb:178:in `<main>'
```

**Comment by cyberarm** [comment]
Are you connected to the internet the first time or two you start the launcher?

**Comment by walksanatora** [comment]
I am connected to internet

**Comment by cyberarm** [comment]
Can you pull and try again?

If it still errors, can you attach the log (in data/logs/) and settings.json (in data/)?

**Comment by walksanatora** [comment]
ah I think school wifi is interferring. gonna check in ~1 hour when I get home then
